'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5448
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("RC.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property b0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b19() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b19", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b23() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b23", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b26() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b26", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b27() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b27", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b28() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b28", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b29() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b29", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b30() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b30", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b31() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b31", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b33() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b33", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b34() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b34", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b35() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b35", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b36() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b36", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b37() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b37", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b38() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b38", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b39() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b39", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b40() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b40", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b41() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b41", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b42() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b42", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b43() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b43", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b44() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b44", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b45() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b45", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b46() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b46", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b47() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b47", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property b9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dip_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dip_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dip_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dip_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dip_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dip_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dip_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dip_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dip_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dip_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dip_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dip_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property indicator_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("indicator_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property indicator_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("indicator_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property matsushita() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("matsushita", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property nec() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nec", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RC_blank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RC_blank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property RC5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RC5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rc6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rc6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SerialConnected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SerialConnected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SerialDisConnected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SerialDisConnected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SHARP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SHARP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
